version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "pan_206"
      POSTGRES_PASSWORD: "pan_206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/HW4_db.sql:/docker-entrypoint-initdb.d/HW4_db.sql
      - ./docker/db/scripts/HW4_db_copy.sql:/docker-entrypoint-initdb.d/HW4_db1.sql
      - ./docker/db/scripts/HW4_db_copy_2.sql:/docker-entrypoint-initdb.d/HW4_db2.sql
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"